### PR TITLE
wip: java static name resolution

### PR DESCRIPTION
**Pull request by adriaanm**
@jodersky, here's a sketch of how I think we could take this last hurdle on scala/scala#5304

### CODE REVIEW

**Comment by adriaanm** [comment]
ah, I just realized we should check whether the current unit is java, not whether the qualifier's symbol is java defined -- I'll `push --force`

**Comment by adriaanm** [comment]
Ok, updated. Handing this one over to you for further investigation :-)

**Comment by jodersky** [comment]
Nice! Thanks for your help

**Comment by jodersky** [comment]
Merged in my main javadoc branch. I took the liberty of amending your commit with some comment cleanup and test fixes.

**Comment by adriaanm** [comment]
Thanks!

**Pull request closed without merging**
